= Guide

== Prerequisites

* docker, docker-machine and docker-compose installed
* PLF version available like below:

[source, bash]
--
$ git clone git@github.com:exoplatform/platform-private-distributions.git && cd platform-private-distributions
$ mvn clean package -Pexo-release,exo-private -Dskip-archive
$ cp -R plf-enterprise-jbosseap-standalone/target/platform*/platform* ../exodev-base-plf/plf43-jboss/plf
$ cp -R plf-enterprise-tomcat-standalone/target/platform*/platform* ../exodev-base-plf/plf43-tomcat/plf
--

== Docker Machine

[source, bash]
--
$ docker-machine create -d virtualbox --virtualbox-cpu-count "4" --virtualbox-memory "4096" exodev-plf
$ eval $(docker-machine env exodev-plf)
--

To check that the conf is ok:
[source, bash]
----
docker-machine inspect exodev-plf
----

=== Start a Docker Machine

[source, bash]
----
docker-machine start exodev-plf
----

=== Stop a Docker Machine

[source, bash]
----
docker-machine stop exodev-plf
----

=== Stop a Docker Machine

== eXo Base

[source, bash]
----
$ cd exodev-base
$ docker build --rm=true --tag=exodev/base:latest .
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
exodev/base         latest              f27148ddd088        13 seconds ago      207.4 MB
centos              7                   0f73ae75014f        9 days ago          172.3 MB
----

== eXo Base JDK

[source, bash]
----
$ cd exodev-base-jdk/jdk7
$ docker build --rm=true --tag=exodev/base-jdk:7 .
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED              VIRTUAL SIZE
exodev/base-jdk     7                   b5ddc5fd7b90        About a minute ago   434.4 MB
exodev/base         latest              f27148ddd088        5 minutes ago        207.4 MB
centos              7                   0f73ae75014f        9 days ago           172.3 MB
----

== eXo Base PLF

=== eXo Base PLF Common

[source, bash]
----
$ cd exodev-base-plf/plf43-common
$ docker build --rm=true --tag=exodev/base-plf:4.3.x .
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
exodev/base-plf     4.3.x               5a5e60723691        8 seconds ago       434.4 MB
exodev/base-jdk     7                   b5ddc5fd7b90        4 minutes ago       434.4 MB
exodev/base         latest              f27148ddd088        7 minutes ago       207.4 MB
centos              7                   0f73ae75014f        9 days ago          172.3 MB
----

===  eXo Base PLF JBoss

[source, bash]
----
$ cd exodev-base-plf/plf43-jboss
$ docker build --rm=true --tag=exodev/plf-jboss:4.3.x .
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
exodev/plf-jboss    4.3.x               2c49d45117a0        13 minutes ago      1.199 GB
exodev/base-plf     4.3.x               fd062cab3937        20 minutes ago      434.4 MB
exodev/base-jdk     7                   b5ddc5fd7b90        52 minutes ago      434.4 MB
exodev/base         latest              f27148ddd088        55 minutes ago      207.4 MB
centos              7                   0f73ae75014f        9 days ago          172.3 MB
$ docker run -p 43180:8080 -p 43190:9990 --name=plf43-jboss  exodev/plf-jboss:4.3.x
$ open http://$(docker-machine ip exodev-plf):43180
----

===  eXo Base PLF Tomcat

[source, bash]
----
$ cd exodev-base-plf/plf43-tomcat
$ docker build --rm=true --tag=exodev/plf-tomcat:4.3.x .
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
exodev/plf-tomcat   4.3.x               bc7d3fb92e2c        19 minutes ago      919.3 MB
exodev/base-plf     4.3.x               fd062cab3937        20 minutes ago      434.4 MB
exodev/base-jdk     7                   b5ddc5fd7b90        52 minutes ago      434.4 MB
exodev/base         latest              f27148ddd088        55 minutes ago      207.4 MB
centos              7                   0f73ae75014f        9 days ago          172.3 MB

$ docker run -p 43280:8080 --name=plf43-tomcat  exodev/plf-tomcat:4.3.x
$ open http://$(docker-machine ip exodev-plf):43280
----

* Remove image

   docker rmi -f exodev/plf-tomcat:4.3.x

===  eXo Base PLF Tomcat/MySQL

[source, bash]
--
$ cd exodev-base-plf/plf43-tomcat-mysql
$ docker build --rm=true --tag=exodev/plf-tomcat-mysql:4.3.x .
$ docker-compose up
$ open http://http://$(docker-machine ip exodev-plf):43380
--

===  eXo Base PLF Tomcat/Oracle

. Run the Oracle Container with SID plf

[source, bash]
--
$ cd exodev-base-plf/plf43-tomcat-oracle
$ docker-compose -f oracle.yml up
--

. Check that it's running

[source, bash]
--
$ open http://$(docker-machine ip exodev-plf):49162/apex
--

[NOTE]
--
Use e following credentials:

* workspace: INTERNAL
* user: ADMIN
* password: oracle
--

. Run the tomcat container

[source, bash]
--
$ docker-compose -f tomcat.yml up
--


== eXo with Addons

=== PLF Tomcat Addons

[source, bash]
----
$ cd exodev-plf-addons/plf43-tomcat-task
$ docker build --rm=true --tag=exodev/plf43-tomcat-task .

$ docker run -p 43380:8080 --name=plf43-tomcat-task  exodev/plf43-tomcat-task
$ open http://http://$(docker-machine ip exodev-plf):43380
----

=== PLF JBoss Addons

[source, bash]
----
$ cd exodev-plf-addons/plf43-jboss-task
$ docker build --rm=true --tag=exodev/plf43-jboss-task .

$ docker run -p 43480:8080 -p 43490:9990 --name=plf43-jboss-task  exodev/plf43-jboss-task
$ open http://http://$(docker-machine ip exodev-plf):43480
----
