plf_tomcat_postgres:
   build: .
   container_name: plf43-tomcat-postgres-task
   ports:
    - "8432:8080"
   links:
    - plf_db:postgres-server

plf_db:
  image: postgres:9.3
  container_name: plf43-tomcat-postgres-task-db
  volumes_from:
    - plf_dbdata
  ports:
   - "5432:5432"
  environment:
    - POSTGRES_USER=plf
    - POSTGRES_PASSWORD=plf
    - POSTGRES_DB=plf

plf_dbdata:
  image: busybox
  container_name: plf43-tomcat-postgres-task-dbdata
  command: /bin/sh
  volumes:
    - /var/lib/postgresql
